[pytest]

# This ensures that the repository root is added to sys.path.
pythonpath = .

# This is the default scope for fixtures in pytest-asyncio.
asyncio_default_fixture_loop_scope = function

markers = integration: marks tests as integration tests (deselect with '-m "not integration"')